### ISSUE TITLE
Missing Reaction env vars for reset password, verify email etc. routes on identity provider

### ISSUE THREAD

**Issue by bayareacoder** [reactioncommerce/proxy-traefik#12]
The ansible playbook only sets `ROOT_URL` in the `.env` file in the `reaction` folder.
Reaction's `api-plugin-accounts` also uses the following env vars which are by default set to `localhost` and thus should be updated to the domain in this playbook. See file `config.js` of this plugin:
```
 REACTION_IDENTITY_PUBLIC_PASSWORD_RESET_URL: str({ devDefault: "http://localhost:4100/account/reset-password/TOKEN" }),
 REACTION_IDENTITY_PUBLIC_VERIFY_EMAIL_URL: str({ devDefault: "http://localhost:4100/#/verify-email/TOKEN" }),
 REACTION_ADMIN_PUBLIC_ACCOUNT_REGISTRATION_URL: str({ devDefault: "http://localhost:4080" })
```

Thus in the playbook:
```
    - name: "Set Reaction's environment variables"
      lineinfile:
        path: "{{ reaction_platform_path }}/reaction/.env"
        regexp: "^ROOT_URL"
        line: "ROOT_URL=https://api.{{ domain }}"
```

should be replaced with:
```
- name: "Set Reaction's environment variables"
      lineinfile:
        path: "{{ reaction_platform_path }}/reaction/.env"
        regexp: "^{{ item.variable }}"
        line: "{{ item.variable }}={{ item.value }}"
      loop:
        - {
            variable: "ROOT_URL",
            value: "https://api.{{ domain }}"
          }
        - {
            variable: "REACTION_IDENTITY_PUBLIC_PASSWORD_RESET_URL",
            value: "https://identity.{{ domain }}/account/reset-password/TOKEN"
          }
        - {
            variable: "REACTION_IDENTITY_PUBLIC_VERIFY_EMAIL_URL",
            value: "https://identity.{{ domain }}/#/verify-email/TOKEN"
          }
        - {
            variable: "REACTION_ADMIN_PUBLIC_ACCOUNT_REGISTRATION_URL",
            value: "https://admin.{{ domain }}"
          }
```
